[package]
name = "txcproxy"
version = "0.2.0"
edition = "2021"
exclude = ["*.py"]

[dependencies]
winapi  = {version = "0.3.8", features = ["winsock2"]}
libtxc = {git = "https://github.com/2dav/libtxc.git"}

[profile.release]
lto = "thin"
