[package]
name = "txcproxy"
version = "0.2.0"
edition = "2021"
exclude = ["*.py"]

[dependencies]
winapi  = {version = "0.3.8", features = ["winsock2"]}
libtxc = "0.2"

[profile.release]
lto = "thin"
