[package]
name = "txcproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi  = {version = "0.3.8", features = ["errhandlingapi", "libloaderapi", "winsock2"]}
libtxc = {git = "https://github.com/2dav/libtxc.git"}

[profile.release]
lto = "thin"
